spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs (qa)"
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267