spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

accounts:
  message: "Welcome to eazybank accounts related local apis"
  contact-details:
    name: "John doe"
    email: "johndoe@example.com"
  on-call-support:
    - "(555) 132 312"
    - "(555) 132 343"
