replicaCount: 1

image:
  repository: apache/kafka
  tag: "4.1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9092

persistence:
  storageClass: ""
  size: 1Gi

podSecurityContext:
  fsGroup: 1000

kafka:
  brokerId: 1
  nodeId: 1
  clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
  offsetsTopicReplicationFactor: 1
  transactionStateLogMinIsr: 1
  transactionStateLogReplicationFactor: 1

resources:
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
    ephemeral-storage: 2Gi